apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.name }}-config
  labels:
    app: {{ .Values.mysql.name }}
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    max_connections={{ .Values.mysql.config.maxConnections }}
    innodb_buffer_pool_size={{ .Values.mysql.config.bufferPoolSize }}
    slow_query_log=1
    slow_query_log_file=/var/log/mysql/slow.log
    long_query_time=2

    [client]
    default-character-set=utf8mb4

    [mysql]
    default-character-set=utf8mb4
